#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.10
# from Racc grammer file "".
#

require 'racc/parser.rb'

  require "lexer"
  require "nodes"

class Parser < Racc::Parser

module_eval(<<'...end grammar.y/module_eval...', 'grammar.y', 176)
  # This code will be put as-is in the Parser class.
  def parse(code, show_tokens=false)
    @tokens = Lexer.new.tokenize(code) # Tokenize the code using our lexer
    puts @tokens.inspect if show_tokens
    do_parse # Kickoff the parsing process
  end
  
  def next_token
    @tokens.shift
  end
...end grammar.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    26,    15,    24,    25,    15,    17,    18,    19,    20,    21,
    22,    23,    30,    26,    27,    24,    25,    15,    17,    18,
    19,    20,    21,    22,    23,    30,    77,    27,    15,    81,
    16,    14,    30,    16,    41,    42,    30,    87,    41,    42,
    39,    40,    73,    73,    14,    26,    16,    24,    25,    53,
    17,    18,    19,    20,    21,    22,    23,    16,    26,    27,
    24,    25,    72,    17,    18,    19,    20,    21,    22,    23,
    51,    30,    27,    41,    42,    48,    14,    26,    47,    24,
    25,    46,    17,    18,    19,    20,    21,    22,    23,    14,
    26,    27,    24,    25,    28,    17,    18,    19,    20,    21,
    22,    23,    73,    86,    27,    85,    90,   nil,    14,    26,
   nil,    24,    25,   nil,    17,    18,    19,    20,    21,    22,
    23,    14,    26,    27,    24,    25,   nil,    17,    18,    19,
    20,    21,    22,    23,   nil,    45,    27,    44,   nil,   nil,
    14,    26,   nil,    24,    25,   nil,    17,    18,    19,    20,
    21,    22,    23,    14,    26,    27,    24,    25,   nil,    17,
    18,    19,    20,    21,    22,    23,   nil,    79,    27,    88,
   nil,   nil,    14,    26,   nil,    24,    25,   nil,    17,    18,
    19,    20,    21,    22,    23,    14,    26,    27,    24,    25,
   nil,    17,    18,    19,    20,    21,    22,    23,   nil,    79,
    27,    78,   nil,   nil,    14,    26,   nil,    24,    25,   nil,
    17,    18,    19,    20,    21,    22,    23,    14,    26,    27,
    24,    25,   nil,    17,    18,    19,    20,    21,    22,    23,
   nil,   nil,    27,   nil,   nil,   nil,    14,    26,   nil,    24,
    25,   nil,    17,    18,    19,    20,    21,    22,    23,    14,
    26,    27,    24,    25,   nil,    17,    18,    19,    20,    21,
    22,    23,   nil,   nil,    27,   nil,   nil,   nil,    14,    26,
   nil,    24,    25,   nil,    17,    18,    19,    20,    21,    22,
    23,    14,    26,    27,    24,    25,   nil,    17,    18,    19,
    20,    21,    22,    23,   nil,   nil,    27,   nil,   nil,   nil,
    14,    26,   nil,    24,    25,   nil,    17,    18,    19,    20,
    21,    22,    23,    14,    26,    27,    24,    25,   nil,    17,
    18,    19,    20,    21,    22,    23,   nil,   nil,    27,   nil,
   nil,   nil,    14,    26,   nil,    24,    25,   nil,    17,    18,
    19,    20,    21,    22,    23,    14,    26,    27,    24,    25,
   nil,    17,    18,    19,    20,    21,    22,    23,   nil,   nil,
    27,   nil,   nil,   nil,    14,    26,   nil,    24,    25,   nil,
    17,    18,    19,    20,    21,    22,    23,    14,    30,    27,
    41,    42,    39,    40,    35,    36,    37,    38,    33,    34,
    32,    31,   nil,   nil,    73,    66,    14,    30,   nil,    41,
    42,    39,    40,    35,    36,    37,    38,    33,    34,    32,
    31,    73,   nil,   nil,    30,   nil,    41,    42,    39,    40,
    35,    36,    37,    38,    33,    34,    32,    31,    30,   nil,
    41,    42,    39,    40,    35,    36,    37,    38,    33,    34,
    32,    31,    30,   nil,    41,    42,    39,    40,    35,    36,
    37,    38,    33,    34,    32,    31,    30,   nil,    41,    42,
    39,    40,    35,    36,    37,    38,    33,    34,    32,    31,
    30,   nil,    41,    42,    39,    40,    35,    36,    37,    38,
    33,    34,    32,    31,    30,   nil,    41,    42,    39,    40,
    35,    36,    37,    38,    33,    34,    32,    31,    30,   nil,
    41,    42,    39,    40,    35,    36,    37,    38,    33,    34,
    32,    31,    30,   nil,    41,    42,    39,    40,    35,    36,
    37,    38,    33,    34,    32,    30,   nil,    41,    42,    39,
    40,    35,    36,    37,    38,    33,    34,    30,   nil,    41,
    42,    39,    40,    35,    36,    37,    38,    30,   nil,    41,
    42,    39,    40,    35,    36,    37,    38,    30,   nil,    41,
    42,    39,    40,    30,   nil,    41,    42,    39,    40,    30,
   nil,    41,    42,    39,    40 ]

racc_action_check = [
     0,     2,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,    64,    73,     0,    73,    73,    73,    73,    73,
    73,    73,    73,    73,    73,    65,    53,    73,    82,    72,
     2,     0,    63,     0,    63,    63,    58,    82,    58,    58,
    58,    58,    48,    47,    73,    79,    73,    79,    79,    30,
    79,    79,    79,    79,    79,    79,    79,    82,    45,    79,
    45,    45,    47,    45,    45,    45,    45,    45,    45,    45,
    28,    62,    45,    62,    62,    25,    79,    14,    24,    14,
    14,    23,    14,    14,    14,    14,    14,    14,    14,    45,
    44,    14,    44,    44,     1,    44,    44,    44,    44,    44,
    44,    44,    85,    80,    44,    80,    86,   nil,    14,    42,
   nil,    42,    42,   nil,    42,    42,    42,    42,    42,    42,
    42,    44,    39,    42,    39,    39,   nil,    39,    39,    39,
    39,    39,    39,    39,   nil,    22,    39,    22,   nil,   nil,
    42,    40,   nil,    40,    40,   nil,    40,    40,    40,    40,
    40,    40,    40,    39,    26,    40,    26,    26,   nil,    26,
    26,    26,    26,    26,    26,    26,   nil,    83,    26,    83,
   nil,   nil,    40,    27,   nil,    27,    27,   nil,    27,    27,
    27,    27,    27,    27,    27,    26,    46,    27,    46,    46,
   nil,    46,    46,    46,    46,    46,    46,    46,   nil,    67,
    46,    67,   nil,   nil,    27,    29,   nil,    29,    29,   nil,
    29,    29,    29,    29,    29,    29,    29,    46,    77,    29,
    77,    77,   nil,    77,    77,    77,    77,    77,    77,    77,
   nil,   nil,    77,   nil,   nil,   nil,    29,    31,   nil,    31,
    31,   nil,    31,    31,    31,    31,    31,    31,    31,    77,
    32,    31,    32,    32,   nil,    32,    32,    32,    32,    32,
    32,    32,   nil,   nil,    32,   nil,   nil,   nil,    31,    33,
   nil,    33,    33,   nil,    33,    33,    33,    33,    33,    33,
    33,    32,    34,    33,    34,    34,   nil,    34,    34,    34,
    34,    34,    34,    34,   nil,   nil,    34,   nil,   nil,   nil,
    33,    35,   nil,    35,    35,   nil,    35,    35,    35,    35,
    35,    35,    35,    34,    36,    35,    36,    36,   nil,    36,
    36,    36,    36,    36,    36,    36,   nil,   nil,    36,   nil,
   nil,   nil,    35,    37,   nil,    37,    37,   nil,    37,    37,
    37,    37,    37,    37,    37,    36,    38,    37,    38,    38,
   nil,    38,    38,    38,    38,    38,    38,    38,   nil,   nil,
    38,   nil,   nil,   nil,    37,    41,   nil,    41,    41,   nil,
    41,    41,    41,    41,    41,    41,    41,    38,    43,    41,
    43,    43,    43,    43,    43,    43,    43,    43,    43,    43,
    43,    43,   nil,   nil,    49,    43,    41,    49,   nil,    49,
    49,    49,    49,    49,    49,    49,    49,    49,    49,    49,
    49,    50,   nil,   nil,    50,   nil,    50,    50,    50,    50,
    50,    50,    50,    50,    50,    50,    50,    50,    52,   nil,
    52,    52,    52,    52,    52,    52,    52,    52,    52,    52,
    52,    52,     3,   nil,     3,     3,     3,     3,     3,     3,
     3,     3,     3,     3,     3,     3,    84,   nil,    84,    84,
    84,    84,    84,    84,    84,    84,    84,    84,    84,    84,
    69,   nil,    69,    69,    69,    69,    69,    69,    69,    69,
    69,    69,    69,    69,    68,   nil,    68,    68,    68,    68,
    68,    68,    68,    68,    68,    68,    68,    68,    70,   nil,
    70,    70,    70,    70,    70,    70,    70,    70,    70,    70,
    70,    70,    54,   nil,    54,    54,    54,    54,    54,    54,
    54,    54,    54,    54,    54,    55,   nil,    55,    55,    55,
    55,    55,    55,    55,    55,    55,    55,    57,   nil,    57,
    57,    57,    57,    57,    57,    57,    57,    56,   nil,    56,
    56,    56,    56,    56,    56,    56,    56,    61,   nil,    61,
    61,    61,    61,    59,   nil,    59,    59,    59,    59,    60,
   nil,    60,    60,    60,    60 ]

racc_action_pointer = [
    -2,    94,    -5,   425,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    75,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   104,    50,    66,    62,   152,   171,    70,   203,
    37,   235,   248,   267,   280,   299,   312,   331,   344,   120,
   139,   363,   107,   361,    88,    56,   184,    29,    28,   380,
   397,   nil,   411,    -7,   495,   508,   530,   520,    19,   546,
   552,   540,    54,    15,    -5,     8,   nil,   167,   467,   453,
   481,   nil,    17,    11,   nil,   nil,   nil,   216,   nil,    43,
    71,   nil,    22,   135,   439,    88,    94,   nil,   nil,   nil,
   nil ]

racc_action_default = [
    -1,   -55,    -2,    -3,    -6,    -7,    -8,    -9,   -10,   -11,
   -12,   -13,   -14,   -15,   -55,   -17,   -18,   -19,   -20,   -21,
   -22,   -23,   -24,   -43,   -55,   -55,   -55,   -55,   -55,    -5,
   -55,   -55,   -55,   -55,   -55,   -55,   -55,   -55,   -55,   -55,
   -55,   -55,   -55,   -55,   -28,   -55,   -55,   -55,   -55,   -55,
   -55,    91,    -4,   -26,   -31,   -32,   -33,   -34,   -35,   -36,
   -37,   -38,   -39,   -40,   -41,   -42,   -16,   -55,   -29,   -44,
   -45,   -46,   -48,   -55,   -51,   -52,   -53,   -28,   -25,   -55,
   -55,   -49,   -55,   -55,   -30,   -55,   -55,   -54,   -27,   -47,
   -50 ]

racc_goto_table = [
    29,     2,    43,    71,    74,    75,    76,    67,     1,    80,
   nil,   nil,   nil,   nil,    49,    50,   nil,    52,   nil,    54,
    55,    56,    57,    58,    59,    60,    61,    62,    63,    64,
    65,   nil,    68,    69,    70,   nil,   nil,   nil,   nil,   nil,
    83,    89,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    68,   nil,    84,   nil,   nil,
   nil,   nil,   nil,   nil,    82,   nil,   nil,   nil,   nil,   nil,
    29 ]

racc_goto_check = [
     4,     2,     3,    15,    15,    15,    15,    14,     1,    16,
   nil,   nil,   nil,   nil,     3,     3,   nil,     3,   nil,     3,
     3,     3,     3,     3,     3,     3,     3,     3,     3,     3,
     3,   nil,     3,     3,     3,   nil,   nil,   nil,   nil,   nil,
    14,    15,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,     3,   nil,     3,   nil,   nil,
   nil,   nil,   nil,   nil,     2,   nil,   nil,   nil,   nil,   nil,
     4 ]

racc_goto_pointer = [
   nil,     8,     1,   -12,    -2,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   -37,   -44,   -63 ]

racc_goto_default = [
   nil,   nil,   nil,     3,     4,     5,     6,     7,     8,     9,
    10,    11,    12,    13,   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  0, 37, :_reduce_1,
  1, 37, :_reduce_2,
  1, 38, :_reduce_3,
  3, 38, :_reduce_4,
  2, 38, :_reduce_5,
  1, 38, :_reduce_6,
  1, 39, :_reduce_none,
  1, 39, :_reduce_none,
  1, 39, :_reduce_none,
  1, 39, :_reduce_none,
  1, 39, :_reduce_none,
  1, 39, :_reduce_none,
  1, 39, :_reduce_none,
  1, 39, :_reduce_none,
  1, 39, :_reduce_none,
  3, 39, :_reduce_16,
  1, 40, :_reduce_none,
  1, 40, :_reduce_none,
  1, 41, :_reduce_19,
  1, 41, :_reduce_20,
  1, 41, :_reduce_21,
  1, 41, :_reduce_22,
  1, 41, :_reduce_23,
  1, 42, :_reduce_24,
  4, 42, :_reduce_25,
  3, 42, :_reduce_26,
  6, 42, :_reduce_27,
  0, 50, :_reduce_28,
  1, 50, :_reduce_29,
  3, 50, :_reduce_30,
  3, 43, :_reduce_31,
  3, 43, :_reduce_32,
  3, 43, :_reduce_33,
  3, 43, :_reduce_34,
  3, 43, :_reduce_35,
  3, 43, :_reduce_36,
  3, 43, :_reduce_37,
  3, 43, :_reduce_38,
  3, 43, :_reduce_39,
  3, 43, :_reduce_40,
  3, 43, :_reduce_41,
  3, 43, :_reduce_42,
  1, 44, :_reduce_43,
  3, 45, :_reduce_44,
  3, 45, :_reduce_45,
  3, 46, :_reduce_46,
  6, 46, :_reduce_47,
  0, 52, :_reduce_48,
  1, 52, :_reduce_49,
  3, 52, :_reduce_50,
  3, 47, :_reduce_51,
  3, 48, :_reduce_52,
  3, 49, :_reduce_53,
  3, 51, :_reduce_54 ]

racc_reduce_n = 55

racc_shift_n = 91

racc_token_table = {
  false => 0,
  :error => 1,
  :IF => 2,
  :ELSE => 3,
  :DEF => 4,
  :CLASS => 5,
  :NEWLINE => 6,
  :NUMBER => 7,
  :STRING => 8,
  :TRUE => 9,
  :FALSE => 10,
  :NIL => 11,
  :IDENTIFIER => 12,
  :CONSTANT => 13,
  :INDENT => 14,
  :DEDENT => 15,
  :WHILE => 16,
  "." => 17,
  "!" => 18,
  "*" => 19,
  "/" => 20,
  "+" => 21,
  "-" => 22,
  ">" => 23,
  ">=" => 24,
  "<" => 25,
  "<=" => 26,
  "==" => 27,
  "!=" => 28,
  "&&" => 29,
  "||" => 30,
  "=" => 31,
  "," => 32,
  "(" => 33,
  ")" => 34,
  ";" => 35 }

racc_nt_base = 36

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "IF",
  "ELSE",
  "DEF",
  "CLASS",
  "NEWLINE",
  "NUMBER",
  "STRING",
  "TRUE",
  "FALSE",
  "NIL",
  "IDENTIFIER",
  "CONSTANT",
  "INDENT",
  "DEDENT",
  "WHILE",
  "\".\"",
  "\"!\"",
  "\"*\"",
  "\"/\"",
  "\"+\"",
  "\"-\"",
  "\">\"",
  "\">=\"",
  "\"<\"",
  "\"<=\"",
  "\"==\"",
  "\"!=\"",
  "\"&&\"",
  "\"||\"",
  "\"=\"",
  "\",\"",
  "\"(\"",
  "\")\"",
  "\";\"",
  "$start",
  "Root",
  "Expressions",
  "Expression",
  "Terminator",
  "Literal",
  "Call",
  "Operator",
  "Constant",
  "Assign",
  "Def",
  "Class",
  "If",
  "While",
  "ArgList",
  "Block",
  "ParamList" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'grammar.y', 45)
  def _reduce_1(val, _values, result)
     result = Nodes.new([]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 46)
  def _reduce_2(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 51)
  def _reduce_3(val, _values, result)
     result = Nodes.new(val) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 52)
  def _reduce_4(val, _values, result)
     result = val[0] << val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 54)
  def _reduce_5(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 55)
  def _reduce_6(val, _values, result)
     result = Nodes.new([]) 
    result
  end
.,.,

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

# reduce 15 omitted

module_eval(<<'.,.,', 'grammar.y', 69)
  def _reduce_16(val, _values, result)
     result = val[1] 
    result
  end
.,.,

# reduce 17 omitted

# reduce 18 omitted

module_eval(<<'.,.,', 'grammar.y', 80)
  def _reduce_19(val, _values, result)
     result = NumberNode.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 81)
  def _reduce_20(val, _values, result)
     result = StringNode.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 82)
  def _reduce_21(val, _values, result)
     result = TrueNode.new 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 83)
  def _reduce_22(val, _values, result)
     result = FalseNode.new 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 84)
  def _reduce_23(val, _values, result)
     result = NilNode.new 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 90)
  def _reduce_24(val, _values, result)
     result = CallNode.new(nil, val[0], []) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 92)
  def _reduce_25(val, _values, result)
     result = CallNode.new(nil, val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 94)
  def _reduce_26(val, _values, result)
     result = CallNode.new(val[0], val[2], []) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 97)
  def _reduce_27(val, _values, result)
     result = CallNode.new(val[0], val[2], val[4]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 101)
  def _reduce_28(val, _values, result)
     result = [] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 102)
  def _reduce_29(val, _values, result)
     result = val 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 103)
  def _reduce_30(val, _values, result)
     result = val[0] << val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 108)
  def _reduce_31(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 109)
  def _reduce_32(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 110)
  def _reduce_33(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 111)
  def _reduce_34(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 112)
  def _reduce_35(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 113)
  def _reduce_36(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 114)
  def _reduce_37(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 115)
  def _reduce_38(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 116)
  def _reduce_39(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 117)
  def _reduce_40(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 118)
  def _reduce_41(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 119)
  def _reduce_42(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 123)
  def _reduce_43(val, _values, result)
     result = GetConstantNode.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 128)
  def _reduce_44(val, _values, result)
     result = SetLocalNode.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 129)
  def _reduce_45(val, _values, result)
     result = SetConstantNode.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 134)
  def _reduce_46(val, _values, result)
     result = DefNode.new(val[1], [], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 136)
  def _reduce_47(val, _values, result)
     result = DefNode.new(val[1], val[3], val[5]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 140)
  def _reduce_48(val, _values, result)
     result = [] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 141)
  def _reduce_49(val, _values, result)
     result = val 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 142)
  def _reduce_50(val, _values, result)
     result = val[0] << val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 147)
  def _reduce_51(val, _values, result)
     result = ClassNode.new(val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 152)
  def _reduce_52(val, _values, result)
     result = IfNode.new(val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 157)
  def _reduce_53(val, _values, result)
     result = WhileNode.new(val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 162)
  def _reduce_54(val, _values, result)
     result = val[1] 
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class Parser
